import AuthProvider from "@/components/provider/AuthProvider";
import "./global.css";
import { Inter } from "next/font/google";
import ThemesProvider from "@/components/provider/ThemeProvider";
import Layout from "@/components/layout";
import ModalProvider from "@/components/provider/ModalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          <ThemesProvider>
            <ModalProvider>
              <Layout>{children}</Layout>
            </ModalProvider>
          </ThemesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
